services:
  chaio-back:
    container_name: chatio-back-dev
    image: chatio-back-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - "3301:3301"
    restart: "always"
    env_file:
      - ../../.env